name: Build qfirehose for AW1000 (qualcommax/ipq807x)

on:
  workflow_dispatch:   # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libncurses5-dev zlib1g-dev gawk \
            git gettext libssl-dev xsltproc rsync wget unzip python3

    - name: Download OpenWrt SDK
      run: |
        wget https://downloads.openwrt.org/snapshots/targets/qualcommax/ipq807x/openwrt-sdk-qualcommax-ipq807x_gcc-12.3.0_musl.Linux-x86_64.tar.xz -O sdk.tar.xz
        tar -xf sdk.tar.xz
        mv openwrt-sdk-* openwrt-sdk

    - name: Fetch qfirehose sources
      run: |
        git clone https://github.com/nippynetworks/qfirehose /tmp/qfirehose-src
        mkdir -p openwrt-sdk/package/custom
        cp -r /tmp/qfirehose-src/package/qfirehose openwrt-sdk/package/custom/
        cp -r /tmp/qfirehose-src/package/luci-app-qfirehose openwrt-sdk/package/custom/

    - name: Build qfirehose packages
      working-directory: openwrt-sdk
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
        make package/custom/qfirehose/compile V=s
        make package/custom/luci-app-qfirehose/compile V=s

    - name: Upload IPK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qfirehose-ipks
        path: |
          openwrt-sdk/bin/packages/*/*/qfirehose*.ipk
          openwrt-sdk/bin/packages/*/*/luci-app-qfirehose*.ipk