name: Build qfirehose for AW1000 (qualcommax/ipq807x)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison gawk \
            libncurses-dev gettext unzip zlib1g-dev libssl-dev python3 file wget zstd

      - name: Download OpenWrt SDK
        run: |
          wget https://archive.openwrt.org/releases/24.10.0-rc2/targets/qualcommax/ipq807x/openwrt-sdk-24.10.0-rc2-qualcommax-ipq807x_gcc-13.3.0_musl.Linux-x86_64.tar.zst
          tar --use-compress-program=unzstd -xvf openwrt-sdk-24.10.0-rc2-qualcommax-ipq807x_gcc-13.3.0_musl.Linux-x86_64.tar.zst
          mv openwrt-sdk-24.10.0-rc2-qualcommax-ipq807x_gcc-13.3.0_musl.Linux-x86_64 openwrt-sdk

      - name: Fetch qfirehose sources
        run: |
          git clone https://github.com/nippynetworks/qfirehose /tmp/qfirehose-src
          mkdir -p openwrt-sdk/package/custom
          cp -r /tmp/qfirehose-src/qfirehose openwrt-sdk/package/custom/
          cp -r /tmp/qfirehose-src/luci-app-qfirehose openwrt-sdk/package/custom/

      - name: Prepare SDK
        run: |
          cd openwrt-sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig

      - name: Build qfirehose
        run: |
          cd openwrt-sdk
          make package/qfirehose/compile V=s
          make package/luci-app-qfirehose/compile V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qfirehose-ipks
          path: openwrt-sdk/bin/packages/**/*.ipk